### ISSUE TITLE
Format notebook at once or automatically calling %%black?

### ISSUE THREAD

**Issue by slochower** [csurfer/blackcellmagic#1]
Any thoughts on enabling the option to format multiple (all...?) cells at once with `%%black`?

**Comment by csurfer** [comment]
@tobinjones has built a Jupiter extension to achieve the same https://github.com/tobinjones/jupyterlab_formatblack Please take a look and close this issue if you think that suffices your need.

**Comment by slochower** [comment]
Looks great, thanks!
