### ISSUE TITLE
New line at end of cell

### ISSUE THREAD

**Issue by neffmallon** [csurfer/blackcellmagic#3]
It seems a little weird to have a new line at the end of the cell. As far as I understand, the purpose for the new line at the end of the file is for versioning, but in jupyder notebooks, the code of each cell is already contained just a single line. Should the default behavior be to not end each cell with a new line?

**Comment by csurfer** [comment]
Magic command is still using black package CLI in its core. So go ahead and set your black package configuration to not do this and it will be respected by the magic command.

**Comment by neffmallon** [comment]
But I do want to keep my new lines at the end of my other files for non-ipynb development and I'd prefer to not set up a separate environment for just my ipy notebooks.  I'm making a pull request now to make this change, feel free to ignore it if you want.
