### ISSUE TITLE
Incompatible with black 19.3b0

### ISSUE THREAD

**Issue by umangv** [csurfer/blackcellmagic#9]
Running with 19.3b0 gives the following error:

```
[blah-blah]python3.6/site-packages/blackcellmagic.py in black(self, line, cell)
     39         if cell:
     40             self.shell.set_next_input(
---> 41                 format_str(src_contents=cell, line_length=line_length),
     42                 replace=True,
     43             )

TypeError: format_str() got an unexpected keyword argument 'line_length'
```

It seems like this is a result of [some changes](https://github.com/ambv/black/pull/618) to how `format_str` works. I believe `line_length` is determined by `mode` now.

Downgrading black by `pip install black==18.9b0` fixes this issue.

**Comment by MarvinT** [comment]
https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/

Have examples for fixing this problem or an alternative method using code-prettify.

**Comment by morberg** [comment]
It seems nbextensions is not compatible with jupyter lab. Is there a way to get black working for jupyter lab as well?

**Comment by micaleel** [comment]
> It seems nbextensions is not compatible with jupyter lab. Is there a way to get black working for jupyter lab as well?

@morberg  `%%black` works quite well with Jupyter Lab. I've been using it for months without issues.

**Comment by morberg** [comment]
> @morberg `%%black` works quite well with Jupyter Lab. I've been using it for months without issues.

I get the same error as @umangv when running 19.3b0. Is that version working fine for you?

**Comment by micaleel** [comment]
My mistake, sorry @morberg. Turns out I'm testing with a different version than 19.3b0.

**Comment by csurfer** [comment]
https://github.com/csurfer/blackcellmagic/pull/8 resolves this issue.
